name: exo3.yml
on:
  workflow_dispatch:
    inputs:
      target:
        description: Environnement à déployer
        required: true
        type: choice
        options: [ staging, production ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24.18.0
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v7
        with:
          name: 'application'
          path: /dist

  test:
    needs: build
    strategy:
      matrix:
        node: [ 20, 22 ]
        os: [ ubuntu-22.04, windows-latest ]
      max-parallel: 2
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.os}}
          cache: npm
      - run: npm ci
      - uses: actions/download-artifact@v7
        with:
          name: application
          path: /dist

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    environment: staging

    steps:
      - uses: actions/download-artifact@v7
        with:
          name: application
          path: /dist
      - name: Simuler le déploiment
        run: echo "${{vars.MY_STAGING_ENV}}"

      - name: Produire le résumé
        shell: bash
        run: |

      - run: echo "## Résultat des tests">> $GITHUB_STEP_SUMMARY


